// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjffqhzeppqsoyhkokpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZmZxaHplcHBxc295aGtva3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NTQ1MzQsImV4cCI6MjA1MDUzMDUzNH0.efOpeyuw1BkFvPPqTxtD0oz5EDQGTCygMsTyawn_5aA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);